In [1]:
import numpy as np
import pandas as pd


In [3]:
from sklearn.datasets import load_iris

In [31]:
iris = load_iris()

In [37]:
df = pd.DataFrame(iris['data'], columns=['sepal_length', 'sepal_width', 'petal_legth', 'petal_width'] )

In [39]:
df['target'] = pd.DataFrame(iris['target'])

In [40]:
df

sepal_length  sepal_width  petal_legth  petal_width  target
0             5.1          3.5          1.4          0.2       0
1             4.9          3.0          1.4          0.2       0
2             4.7          3.2          1.3          0.2       0
3             4.6          3.1          1.5          0.2       0
4             5.0          3.6          1.4          0.2       0
5             5.4          3.9          1.7          0.4       0
6             4.6          3.4          1.4          0.3       0
7             5.0          3.4          1.5          0.2       0
8             4.4          2.9          1.4          0.2       0
9             4.9          3.1          1.5          0.1       0
10            5.4          3.7          1.5          0.2       0
11            4.8          3.4          1.6          0.2       0
12            4.8          3.0          1.4          0.1       0
13            4.3          3.0          1.1          0.1       0
14            5.8          4.0          1.2          0.2       0
15            5.7          4.4          1.5          0.4       0
16            5.4          3.9          1.3          0.4       0
17            5.1          3.5          1.4          0.3       0
18            5.7          3.8          1.7          0.3       0
19            5.1          3.8          1.5          0.3       0
20            5.4          3.4          1.7          0.2       0
21            5.1          3.7          1.5          0.4       0
22            4.6          3.6          1.0          0.2       0
23            5.1          3.3          1.7          0.5       0
24            4.8          3.4          1.9          0.2       0
25            5.0          3.0          1.6          0.2       0
26            5.0          3.4          1.6          0.4       0
27            5.2          3.5          1.5          0.2       0
28            5.2          3.4          1.4          0.2       0
29            4.7          3.2          1.6          0.2       0
..            ...          ...          ...          ...     ...
120           6.9          3.2          5.7          2.3       2
121           5.6          2.8          4.9          2.0       2
122           7.7          2.8          6.7          2.0       2
123           6.3          2.7          4.9          1.8       2
124           6.7          3.3          5.7          2.1       2
125           7.2          3.2          6.0          1.8       2
126           6.2          2.8          4.8          1.8       2
127           6.1          3.0          4.9          1.8       2
128           6.4          2.8          5.6          2.1       2
129           7.2          3.0          5.8          1.6       2
130           7.4          2.8          6.1          1.9       2
131           7.9          3.8          6.4          2.0       2
132           6.4          2.8          5.6          2.2       2
133           6.3          2.8          5.1          1.5       2
134           6.1          2.6          5.6          1.4       2
135           7.7          3.0          6.1          2.3       2
136           6.3          3.4          5.6          2.4       2
137           6.4          3.1          5.5          1.8       2
138           6.0          3.0          4.8          1.8       2
139           6.9          3.1          5.4          2.1       2
140           6.7          3.1          5.6          2.4       2
141           6.9          3.1          5.1          2.3       2
142           5.8          2.7          5.1          1.9       2
143           6.8          3.2          5.9          2.3       2
144           6.7          3.3          5.7          2.5       2
145           6.7          3.0          5.2          2.3       2
146           6.3          2.5          5.0          1.9       2
147           6.5          3.0          5.2          2.0       2
148           6.2          3.4          5.4          2.3       2
149           5.9          3.0          

In [41]:
X = df.drop('target', axis=1)

In [42]:
y = df['target']

In [43]:
y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
120    2
121    2
122    2
123    2
124    2
125    2
126    2
127    2
128    2
129    2
130    2
131    2
132    2
133    2
134    2
135    2
136    2
137    2
138    2
139    2
140    2
141    2
142    2
143    2
144    2
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [46]:
import tensorflow as tf


In [49]:
#FEATURE COLUMNS

In [50]:
X.columns

Index(['sepal_length', 'sepal_width', 'petal_legth', 'petal_width'], dtype='object')

In [51]:
feat_cols = []
for col in X.columns:
    feat_cols.append(tf.feature_column.numeric_column(col))

In [52]:
feat_cols

[_NumericColumn(key='sepal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sepal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_legth', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [73]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, batch_size=10, num_epochs=5, shuffle=True)

In [74]:
classifier = tf.estimator.DNNClassifier(hidden_units=[10,10],n_classes=3, feature_columns=feat_cols )

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\HP\\AppData\\Local\\Temp\\tmp2s0873wi', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001B2F8CB9BE0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [89]:
classifier.train(input_fn=input_func, steps=30)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\HP\AppData\Local\Temp\tmp2s0873wi\model.ckpt-103
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 103 into C:\Users\HP\AppData\Local\Temp\tmp2s0873wi\model.ckpt.
INFO:tensorflow:loss = 3.548279, step = 104
INFO:tensorflow:Saving checkpoints for 133 into C:\Users\HP\AppData\Local\Temp\tmp2s0873wi\model.ckpt.
INFO:tensorflow:Loss for final step: 2.8053105.


In [90]:
pred_fn = tf.estimator.inputs.pandas_input_fn(x=X_test, batch_size=len(X_test), shuffle=False)

In [91]:
predictions = list(classifier.predict(input_fn=pred_fn))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\HP\AppData\Local\Temp\tmp2s0873wi\model.ckpt-133
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [92]:
final_preds = []

for pred in predictions:
    final_preds.append(pred['class_ids'][0])

In [93]:
from sklearn.metrics import confusion_matrix, classification_report

In [94]:
print(confusion_matrix(y_test, final_preds))

[[11  0  0]
 [ 0 17  0]
 [ 0  1 16]]


In [95]:
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.94      1.00      0.97        17
           2       1.00      0.94      0.97        17

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

